"""Free one-page emergency contact card — the landing wedge payload.

Generated by the same renderer as the paid products; given away in exchange
for an email address on the landing page.
"""

from __future__ import annotations

from .theme import PageFn, Page, MARGIN, ACCENT, MUTED, INK

FREEBEE_FIELDS = [
    ("name", "Full name"),
    ("phone", "Phone"),
    ("contact1", "Emergency contact (name)"),
    ("contact1_phone", "Emergency contact (phone)"),
    ("contact2", "Second contact (name)"),
    ("contact2_phone", "Second contact (phone)"),
    ("blood_type", "Blood type"),
    ("allergies", "Allergies"),
    ("doctor", "Doctor"),
    ("doctor_phone", "Doctor's phone"),
    ("insurance", "Insurance"),
    ("policy", "Policy number"),
]

_BLANK = "\u2014"


def build_emergency_card(fields: dict, paper: str = "letter") -> list[PageFn]:
    def page(ctx: Page, n: int, total: int):
        w = ctx.w
        m = MARGIN
        ctx.rect(0, 0, w, 8, fill=ACCENT)
        ctx.text(m, 40, "PaperLife \u2014 free card", size=9.0, color=MUTED)
        ctx.text(w / 2, 96, "EMERGENCY CONTACT CARD", size=20.0, font="bold",
                 align="center")
        ctx.text(w / 2, 122, "Keep in your wallet. Make one for every household member.",
                 size=10.0, color=MUTED, align="center")
        ctx.line(m, 148, w - m, 148, color=ACCENT, width=1.0)

        def row(label, value, y):
            ctx.text(m, y, label, size=8.0, font="bold", color=MUTED)
            ctx.text(m, y + 13, str(value or "").strip() or _BLANK, size=11.0)
            ctx.line(m, y + 30, w - m, y + 30, color=MUTED, width=0.5)

        y = 176
        row("FULL NAME", fields.get("name"), y)
        row("PHONE", fields.get("phone"), y + 40)
        row("EMERGENCY CONTACT 1", f"{fields.get('contact1') or ''}  {fields.get('contact1_phone') or ''}", y + 80)
        row("EMERGENCY CONTACT 2", f"{fields.get('contact2') or ''}  {fields.get('contact2_phone') or ''}", y + 120)
        row("BLOOD TYPE", fields.get("blood_type"), y + 160)
        row("ALLERGIES", fields.get("allergies"), y + 200)
        row("DOCTOR", f"{fields.get('doctor') or ''}  {fields.get('doctor_phone') or ''}", y + 240)
        row("INSURANCE", f"{fields.get('insurance') or ''}  {fields.get('policy') or ''}", y + 280)
        ctx.foot(n, total)

    return [page]
